TEST_ARRAY=(
01_RDT_A_MONITORLLC_MEMBW_TWOPQOSINSTANCES_STRESS_L
02_RDT_A_MONITORLLC_MEMBW_COREGROUP_STRESS_L
03_RDT_A_MONITORLLC_MEMBW_MULTIPLECPUCORES_STRESS_L
04_RDT_B_CATALLOCATION_LLC_MEMTESTER_RDTSET
05_RDT_B_CMTMONITOR_LLC_MEMTESTER
06_RDT_B_CPUAFFINITY_RDTSET
07_RDT_B_MBAALLOCATION_MEMORY
08_RDT_C_MULTICHASELATENCY_STREAM
09_RDT_C_MBA_SREAM_TWOCORES_INDEPENDENTLY
10_RDT_B_MBAALLOCATION_MEMORY_MEMTESTER_RDTSET
11_RDT_A_MBMSTATISTICS_MBL_STRESS_L
12_RDT_B_MBAALLOCATION_MEMORY_MEMTESTER_RDTSET_LIBINTERFACE
13_RDT_C_CAT_EFFECTIVENESS_LATMEMRD_LMBENCHLATENCY
14_RDT_B_MBMMONITOR_MEMORY_MEMTESTER
15_RDT_B_CATALLOCATION_LLC
16_RDT_C_MBM_MLC
17_RDT_C_MBM_MEASUREMENTS_MEMBWTRAFFIC_VSPCM
18_RDT_A_MBMSTATISTICS_MBR_STRESS
)

NUM_TESTS=${#TEST_ARRAY[@]}
NUM_PASS=0
TIMESTAMP=`date +%m_%d_%Y_%Hh%Mm%Ss`
EXECUTION_LOG=`pwd`"/execution_$TIMESTAMP.log"
echo "$TIMESTAMP" > $EXECUTION_LOG
echo "---------" | tee -a $EXECUTION_LOG
for i in "${TEST_ARRAY[@]}"; do
	echo "Execute:  $i" | tee -a $EXECUTION_LOG
	cd $i
	TIMESTAMP=`date +%m_%d_%Y_%Hh%Mm%Ss`
	SCRIPT_LOG="testscript_$TIMESTAMP.log"
	sh testscript.sh > $SCRIPT_LOG
	ERROR=`grep -i "error\|fail\|warn" $SCRIPT_LOG`
	ERROR_COUNT=`grep -i "error\|fail\|warn" $SCRIPT_LOG -c`
	if [[ $ERROR_COUNT -eq 0 ]]; then
		RES="Pass"
		NUM_PASS=$((NUM_PASS + 1))
	else
		RES="See details..."
	fi
	echo "Result:  " $RES | tee -a $EXECUTION_LOG
	echo $ERROR | tee -a $EXECUTION_LOG
	echo "---------" | tee -a $EXECUTION_LOG
	cd - &> /dev/null
done
echo ""
echo "done" | tee -a $EXECUTION_LOG
echo "$NUM_PASS / $NUM_TESTS tets passed.  Note that some tests couldn't be determined pass/fail in script and require manual interpretation" | tee -a $EXECUTION_LOG
echo "See $EXECUTION_LOG for details"
echo ""

